[workspace]
resolver = "2"
members = [
    "programs/*",
    "rust-sdk/client",
    "rust-sdk/whirlpool",
    "rust-sdk/core"
]
exclude = [
    "rust-sdk",
    "ts-sdk",
    "docs",
    "examples"
]

[profile.release]
overflow-checks = true